GET http://localhost:8888/friends%20tv%20show

###

GET http://localhost:8888/friends%20tv%20show/paragraphs

###

GET http://localhost:8888/friends%20tv%20show/words

###

GET http://localhost:8888/friends%20tv%20show/paragraphs/3

###
GET http://localhost:8888/friends%20tv%20show/words/100

###

# error = quantity of words is too low
GET http://localhost:8888/friends%20tv%20show/words/10

###

# error = quantity of paragraphs is too low
GET http://localhost:8888/friends%20tv%20show/paragraphs/0

###

GET http://localhost:8888/friends%20tv%20show/paragraphs/2/html

###

GET http://localhost:8888/friends%20tv%20show/paragraphs/4/plain

###

# error: unknown format argument
GET http://localhost:8888/friends%20tv%20show/paragraphs/3/foo

###

GET http://localhost:8888/?query=friends%20tv%20show

###

GET http://localhost:8888/?query=friends%20tv%20show&quantity=3&format=html

###
wordsPerSentenceMin
GET http://localhost:8888/
content-type: application/json

{
    "query": "harry potter",
    "unit": "words",
    "quantity": 100,
    "format": "html"
}

###

GET http://localhost:8888/friends%20tv%20show/paragraphs/2/html/4/12/7/20

###

GET http://localhost:8888/?query=friends%20tv%20show&quantity=3&format=html&sentencesPerParagraphMin=4&sentencesPerParagraphMax=12&wordsPerSentenceMin=7&wordsPerSentenceMax=20

###

GET http://localhost:8888/
content-type: application/json

{
    "query": "harry potter",
    "quantity": 3,
    "format": "html",
    "sentencesPerParagraphMin": 4,
    "sentencesPerParagraphMax": 1200,
    "wordsPerSentenceMin": 7,
    "wordsPerSentenceMax": 20
}

###

GET http://localhost:8888/
content-type: application/json

{
    "query": "harry potter",
    "quantity": 3,
    "format": "html",
    "requirements": {
        "sentencesPerParagraphMin": 4,
        "sentencesPerParagraphMax": 1200,
        "wordsPerSentenceMin": 7,
        "wordsPerSentenceMax": 20
    }
}